<MyLayout>:
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        TextInput:
            id: cal_input
            text: "0"
            halign: "right"
            font_size: "75sp"
            size_hint_y: 0.2
            size_hint_x: 1
            padding: [0, 110, 60, 10]

        BoxLayout:
            orientation: "vertical"
            size_hint_y: 0.8
            spacing: 10
            padding: 10

            BoxLayout:
                orientation: "horizontal"
                spacing: 10

                Button:
                    id: clear
                    font_size: 32
                    text: "AC"
                    background_color: [0.5, 0.5, 0.5, 1]
                    on_press: root.clear()
                Button:
                    font_size: 32
                    text: "+/-"
                    background_color: [0.5, 0.5, 0.5, 1]
                Button:
                    font_size: 32
                    text: "%"
                    background_color: [0.5, 0.5, 0.5, 1]
                Button:
                    font_size: 32
                    text: "÷"
                    background_color: [1.0, 0.8, 0.4, 1]
                    on_press: root.buttonpress("÷")

            BoxLayout:
                orientation: "horizontal"
                spacing: 10

                Button:
                    font_size: 32
                    text: "7"
                    on_press: root.buttonpress(7)
                Button:
                    font_size: 32
                    text: "8"
                    on_press: root.buttonpress(8)
                Button:
                    font_size: 32
                    text: "9"
                    on_press: root.buttonpress(9)
                Button:
                    font_size: 32
                    text: "x"
                    background_color: [1.0, 0.8, 0.4, 1]
                    on_press: root.buttonpress("x")

            BoxLayout:
                orientation: "horizontal"
                spacing: 10

                Button:
                    font_size: 32
                    text: "4"
                    on_press: root.buttonpress(4)
                Button:
                    font_size: 32
                    text: "5"
                    on_press: root.buttonpress(5)
                Button:
                    font_size: 32
                    text: "6"
                    on_press: root.buttonpress(6)
                Button:
                    font_size: 32
                    text: "-"
                    background_color: [1.0, 0.8, 0.4, 1]
                    on_press: root.buttonpress("-")

            BoxLayout:
                orientation: "horizontal"
                spacing: 10

                Button:
                    font_size: 32
                    text: "1"
                    on_press: root.buttonpress(1)
                Button:
                    font_size: 32
                    text: "2"
                    on_press: root.buttonpress(2)
                Button:
                    font_size: 32
                    text: "3"
                    on_press: root.buttonpress(3)
                Button:
                    font_size: 32
                    text: "+"
                    background_color: [1.0, 0.8, 0.4, 1]
                    on_press: root.buttonpress("+")

            BoxLayout:
                orientation: "horizontal"
                spacing: 10

                Button:
                    font_size: 32
                    text: "0"
                    size_hint_x: 2
                    on_press: root.buttonpress(0)
                Button:
                    font_size: 32
                    text: "."
                    on_press: root.buttonpress(".")
                Button:
                    font_size: 32
                    text: "="
                    background_color: [1.0, 0.8, 0.4, 1]
                    on_press: root.buttonpress("=")
